-- MySQL Script generated by MySQL Workbench
-- Wed Apr 13 14:39:23 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema personasymascotas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `personasymascotas` ;

-- -----------------------------------------------------
-- Schema personasymascotas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `personasymascotas` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema personas_y_mascotas
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `personasymascotas`.`persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `personasymascotas`.`persona` ;

CREATE TABLE IF NOT EXISTS `personasymascotas`.`persona` (
  `idpersona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  PRIMARY KEY (`idpersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `personasymascotas`.`mascota`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `personasymascotas`.`mascota` ;

CREATE TABLE IF NOT EXISTS `personasymascotas`.`mascota` (
  `idmascota` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `raza` VARCHAR(45) NULL,
  `persona_idpersona` INT NOT NULL,
  PRIMARY KEY (`idmascota`),
  INDEX `fk_mascota_persona_idx` (`persona_idpersona` ASC) VISIBLE,
  CONSTRAINT `fk_mascota_persona`
    FOREIGN KEY (`persona_idpersona`)
    REFERENCES `mydb`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
