-- MySQL Script generated by MySQL Workbench
-- Wed Apr 13 10:57:30 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mercado
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mercado` ;

-- -----------------------------------------------------
-- Schema mercado
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mercado` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mercado` ;

-- -----------------------------------------------------
-- Table `mercado`.`vendedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mercado`.`vendedor` ;

CREATE TABLE IF NOT EXISTS `mercado`.`vendedor` (
  `idvendedor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `dni` INT NULL,
  `direccion` VARCHAR(45) NULL,
  `fecha_nacimiento` DATE NULL,
  `salario` DECIMAL(5,2) NULL,
  PRIMARY KEY (`idvendedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mercado`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mercado`.`cliente` ;

CREATE TABLE IF NOT EXISTS `mercado`.`cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `dni` INT NULL,
  `direccion` VARCHAR(45) NULL,
  `fecha_nacimiento` DATE NULL,
  `vendedor_idvendedor` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_cliente_vendedor_idx` (`vendedor_idvendedor` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_vendedor`
    FOREIGN KEY (`vendedor_idvendedor`)
    REFERENCES `mercado`.`vendedor` (`idvendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mercado`.`facturacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mercado`.`facturacion` ;

CREATE TABLE IF NOT EXISTS `mercado`.`facturacion` (
  `idfacturacion` INT NOT NULL AUTO_INCREMENT,
  `fecha_compra` DATE NULL,
  `vendedor_idvendedor` INT NOT NULL,
  PRIMARY KEY (`idfacturacion`),
  INDEX `fk_facturacion_vendedor1_idx` (`vendedor_idvendedor` ASC) VISIBLE,
  CONSTRAINT `fk_facturacion_vendedor1`
    FOREIGN KEY (`vendedor_idvendedor`)
    REFERENCES `mercado`.`vendedor` (`idvendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mercado`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mercado`.`producto` ;

CREATE TABLE IF NOT EXISTS `mercado`.`producto` (
  `idproducto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `precio_unitario` DECIMAL(4,2) NULL,
  `cantidad` INT NULL,
  `stock_minimo` INT NULL,
  `facturacion_idfacturacion` INT NOT NULL,
  PRIMARY KEY (`idproducto`),
  INDEX `fk_producto_facturacion1_idx` (`facturacion_idfacturacion` ASC) VISIBLE,
  CONSTRAINT `fk_producto_facturacion1`
    FOREIGN KEY (`facturacion_idfacturacion`)
    REFERENCES `mercado`.`facturacion` (`idfacturacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
