-- MySQL Script generated by MySQL Workbench
-- Tue Apr 12 18:30:38 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`artista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`artista` ;

CREATE TABLE IF NOT EXISTS `mydb`.`artista` (
  `idartista` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idartista`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`album`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`album` ;

CREATE TABLE IF NOT EXISTS `mydb`.`album` (
  `idalbum` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `artista_idartista` INT NOT NULL,
  PRIMARY KEY (`idalbum`),
  INDEX `fk_album_artista2_idx` (`artista_idartista` ASC) VISIBLE,
  CONSTRAINT `fk_album_artista2`
    FOREIGN KEY (`artista_idartista`)
    REFERENCES `mydb`.`artista` (`idartista`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL DEFAULT '\"\"',
  `contraseña` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`lista_de_reproduccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`lista_de_reproduccion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`lista_de_reproduccion` (
  `id_lista` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_lista`),
  INDEX `fk_lista_de_reproduccion_usuario1_idx` (`usuario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_lista_de_reproduccion_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `mydb`.`usuario` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`cancion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cancion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cancion` (
  `idcancion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `duracion` INT NULL DEFAULT NULL,
  `lista_de_reproduccion_id_lista` INT NOT NULL,
  `artista_idartista` INT NOT NULL,
  `album_idalbum` INT NOT NULL,
  PRIMARY KEY (`idcancion`),
  INDEX `fk_cancion_lista_de_reproduccion_idx` (`lista_de_reproduccion_id_lista` ASC) VISIBLE,
  INDEX `fk_cancion_artista1_idx` (`artista_idartista` ASC) VISIBLE,
  INDEX `fk_cancion_album1_idx` (`album_idalbum` ASC) VISIBLE,
  CONSTRAINT `fk_cancion_album1`
    FOREIGN KEY (`album_idalbum`)
    REFERENCES `mydb`.`album` (`idalbum`),
  CONSTRAINT `fk_cancion_artista1`
    FOREIGN KEY (`artista_idartista`)
    REFERENCES `mydb`.`artista` (`idartista`),
  CONSTRAINT `fk_cancion_lista_de_reproduccion`
    FOREIGN KEY (`lista_de_reproduccion_id_lista`)
    REFERENCES `mydb`.`lista_de_reproduccion` (`id_lista`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
